### ISSUE TITLE
在使用Java17-20的GTNH2.3.2中没有效果

### ISSUE THREAD

**Issue by Yecgaa1** [vfyjxf/NEI-Utilities#7]
加载了该模组但似乎没有生效，还是说暂不兼容
![image](https://user-images.githubusercontent.com/38446391/230375340-c6881b4f-0e39-4009-a84d-32a424cc4dc1.png)
![image](https://user-images.githubusercontent.com/38446391/230375380-213fc7e4-f747-4957-9892-d77718c99865.png)

**Comment by chendijun527** [comment]
俺也一样

**Comment by Discreater** [comment]
报错如下
```
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NoSuchFieldException: modifiers
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2707)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.github.vfyjxf.neiutilities.nei.NEIConfig.setItemPanel(NEIConfig.java:36)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.github.vfyjxf.neiutilities.NEIUtilities.init(NEIUtilities.java:43)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5095)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:19:20] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Discreater** [comment]
修了一下，可以用，但是有一些问题。

>  拖拽历史栏的物品的时候会有问题（拖拽中的物品变成下一页的物品，而不是历史栏上的物品）。

可以到这里下载： https://github.com/Discreater/NEI-Utilities/releases/tag/0.2.0-j9
